### ISSUE TITLE
Insert IDNA-urls in human readable format

### ISSUE THREAD

**Issue by Lucki** [thosmos/filelink-owncloud#4]
When using an [IDNA](https://en.wikipedia.org/wiki/Internationalized_domain_name)-url while uploading the encrypted, [punycoded](https://en.wikipedia.org/wiki/Punycode) url gets pasted into the message body instead of the url being in the human readable format.

Please auto insert the human readable url instead of the encrypted url.

**Comment by thosmos** [comment]
The "punycoded" URL is generated by NextCloud/OwnCloud for public links.  This plugin uses whatever the server generates as the public link for the file and I can not "choose" what it will be.
