### ISSUE TITLE
Nexcloud

### ISSUE THREAD

**Issue by marcatsmci** [thosmos/filelink-owncloud#5]
Hi !

Glad to see this extension reborn ! Thanks !

Any chance to have a version for Nextcloud (logo & url) ?

BR,
Marc

**Comment by thosmos** [comment]
I submitted a PR to the nextcloud/nextcloud-filelink repo with a nextcloud-branded version of this module https://github.com/nextcloud/nextcloud-filelink/pull/85.  However, it appears there's a different effort that claims to supersede my PR https://github.com/joendres/nextcloud-filelink.  Have you taken a look at that?
